// src/components/achievementsData.js
const achievementsData = [
  
  {
    id: 19,
  name:"CYSE Students",
  date: "Dec 2023",
  achievement: "Won SIH 2023",
  details: "Grand Finale of Smart India Hackathon 2023 conducted at Nodal center OP Jindal University Raigarh. Team was mentored by faculty Ms. Meghali kalyankar and Ms. Prajakta Pote.",
    link: "https://example.com/smart-india-hackathon",
  banner: "/img/achievements/SIHOP.jpg",
},
{
  id: 5,
  name: "CYSE Department",
  date: "July to Oct 2024",
  achievement: "Cybersecurity Awareness by Team",
  details: "Exposing Digital Deceptions: Skits on Deepfake Scams, Kidnapping Hoaxes, and Social Media Blackmail In a creative and powerful initiative, Team Cyber Surksha Mandal performed engaging skits to shed light on the alarming rise of deepfake technology, misinformation, and online fraud. Through compelling performances at schools, public spaces, and colleges",
  link: "https://example.com/awareness",
  banner: "/img/achievements/natak.png",
},
{
  id: 11,
  name:"Cybersecurity Department",
  date:"April 6th, 2024",
  achievement: "Team Triumphs at Cython 2024",
  details:"SAKEC Cyber Security Department Team (CyHEX Infotech Private Limited Start-up: https://cyhex.co/) has emerged victorious at the Cython 2024 Hackathon, held on April 6th, 2024, and organized by FITT-IIT Delhi. Our team has showcased remarkable talent and dedication, earning a prestigious win and a prize money of 3 Lakhs INR.",
link: "https://example.com/hackathon",
 banner: "/img/achievements/cyhax-winner.jpg",
},
{
  id: 41,
name:"CYSE Students",
 date: "Jan 2023",
achievement:"Secured 1st at CTF challenge",
 details:"The team was awarded with a certificate and cash prize. Organized by S.I.W.S College Wadala, Mumbai.",
link:"https://example.com/ctf-challenge",
banner: "/img/achievements/CTF-heist.jpg",
},
{
  id: 12,
  name:"CYSE Department",
  date:"April 2024",
   achievement: "Magazine Launch",
    details: "Industry Insights: From finance to entertainment, healthcare to education, each industry grapples with its own unique challenges when it comes to combating deepfake manipulation. Our Industry Insights segment sheds light on these nuances, offering expert perspectives and innovative strategies tailored to specific sectors.",
  link: "https://example.com/magazine-launch",
  banner: "/img/achievements/abhayan-2.jpg",
},
{
  id: 13,
 name:"CYSE students",
 date:"April 2024",
  achievement: "TrustTrace",
   details: "Introduce TrustTrace, the culmination of our students’ tireless efforts to combat the rising tide of deepfakes.",
 link: "https://example.com/project",
   banner: "/img/achievements/trustrace.jpg",
},
  {
      id: 2,
      name: "Dr. Nilakshi Jain",
      date: "28th August 2024",
      achievement: "Expert Talk on threat hunting",
      details: "AT CHANDIGARH UNIVERSITY, in collaboration with its CyberPeace Centre of Excellence under the AIT CSE department, conducted an Expert talk session on threat hunting. This session provided a deep dive into using advanced threat sensors, combining theoretical knowledge with practical cybersecurity skills.",
      link: "https://example.com/expert-talk",
       banner: "/img/achievements/session.jpg"
  },
  {
    id: 1,
    name: "Dr. Rupali Vairagade",
    date: "14th October 2024",
    achievement: "Insightful Tech Talk",
    details: "Delivered an insightful Tech Talk on “India Future Ready: Safety & Cybersecurity Planning Considerations” to Second-Year students from the Computer Engineering Department at K.J. Somaiya Polytechnic under the banner of SAKEC CyberPeace Center of Excellence The session, held on 14th October 2024, empowered students with key insights into the future of cybersecurity and strategies for ensuring safety in the evolving digital landscape.",
    link: "https://example.com/tech-talk",
    banner: "/img/achievements/rupalimaam.png"
  },
  {
    id: 3,
    name: "Dr. Nilakshi Jain",
    date: "June 2024",
    achievement: "IT Engineer Panel",
    details: "Guided and uplifted society. She has been a part of the जैन युवा संघ मुंबई as an IT panelist, sharing insights and guiding aspiring engineers.",
    link: "https://example.com/it-panel",
    banner: "/img/achievements/itpanel.png",
  },
   {
       id: 4,
      name: "Dr. Nilakshi Jain",
      date: "30th – 31st August 2024",
      achievement: "Best HoD of the Year",
      details: "CSI-E-TechNext 2024 Industry Academia Conference & Academia Awards (2024) based on the theme : Bridging the Future: Industry Vs Academia Digital Diversity Synergy on Emerging IT Ideas & Trends – Powered India’s New Education Policy",
      link: "https://example.com/hod-award",
      banner: "/img/achievements/besthod.png",
  },
  
  {
      id: 6,
     name: "CYSE Department",
    date: "July 2024",
    achievement: "Magazine A Spectacular Launch",
     details: "Our magazine’s latest issue is set to revolutionize the way we confront the challenges of deepfake technology. With digital manipulation on the rise, it’s more important than ever to equip ourselves with the knowledge and tools to navigate this complex landscape",
    link: "https://example.com/magazine",
       banner: "/img/achievements/abhayan-2.jpg",
    },
  {
      id: 7,
      name: "Ms. Vishakha Shinde, CYSE",
      date: "July 2024",
      achievement: "Earned Cloud Security Engineer Certification",
       details:"The EC-Council’s C|CSE certification stands at the forefront of this transformation. This vendor-neutral certification highlights essential cloud security practices, technologies, and frameworks. Achieving this global certification requires immense dedication, hard work, and expertise in cloud computing.",
        link: "https://example.com/certified-cloud-security-engineer",
       banner: "/img/achievements/vishakha.jpg",
  },
  {
      id: 8,
    name: "Dr. Asha Durafe Dr. Rashmi Malvankar Uday Bhave Dr.Pravin Vishnu Shinde Atul Kachare Shubham Bakal Satish Bangal",
     date: "April 2024",
     achievement: "Trained Navy officers",
      details:"Successfully conducted training for Navy officers in CCNA, Advanced SQL, and PHP under the supervision of Dr. Nilakshi Jain in SAKEC. Officers including LEM (R), LEM (P), LCOM(TEL), LS(GW), LAM, RPO, LPM, POME, PO(UW), LA (AH), POA (AH), LT CDR, and LT CDR-AT-ARMS participated in this training.",
    link: "https://example.com/navy-training",
      banner: "/img/achievements/navy.png",
  },
  {
    id: 9,
    name: "Council Members, CYSE",
      date:"April 2024",
     achievement:"Board members contributions",
     details:"Congratulated to the SAKEC Cyber Security Student Board members for their exceptional contributions throughout the academic year 2023-24. Their dedication and hard work have undoubtedly made a significant impact.",
    link: "https://example.com/student-board",
    banner: "/img/achievements/council.png",
  },
  {
      id: 10,
     name: "SAKEC CyberPeace Center",
      date:"13 Feb 2024",
      achievement: "Hosted distinguished delegation",
       details: "SAKEC CyberPeace Center of Excellence was honored to host a distinguished delegation comprising esteemed representatives from the Prime Minister’s Office, Sun Group Enterprises, and the Israel National Cyber Directorate (INCD). Dr. Nilakshi Jain, representing the SAKEC CyberPeace Centre of Excellence, had the privilege of showcasing our operations, state-of-the-art facilities, impactful contributions, and notable achievements. Students from SAKEC’s Cyber Security department presented their projects, showcasing their skills and innovative ideas. We express our gratitude for the insightful discussions and eagerly anticipate further engagements aimed at advancing cyber peace and security on a global scale.",
      link: "https://example.com/cyberpeace-center",
    banner: "/img/achievements/meeting.png",
  },
  
 
 
  {
      id: 14,
      name:"Dr. Shwetambari Borade",
     date:"26th February 2024",
      achievement: "Received German Patent",
       details: "Patent Title: “System for developing a deep scattering convolutional network for cosmetic skin classification” Patent Granted: 26th February 2024 Application No.: 20 2024 100 262.8",
      link: "https://example.com/german-patent",
     banner: "/img/achievements/cosmetic.jpg",
  },
    {
        id: 15,
    name: "CYSE Student",
     date:"Jan 2024",
     achievement: "CEH Course Performance",
     details: "SAKEC students, faculties and external participants have shown great interest and exhibited remarkable performance in EC Council Certified Ethical Hackers (C|EH) course. Total of 24 candidates registered and 23 candidates successfully completed the certification.",
      link: "https://example.com/ethical-hackers",
      banner: "/img/achievements/ceh3.jpg",
    },
    {
         id: 16,
      name:"Dr. Shwetambari Borade",
      date: "February 16, 2024",
       achievement: "Cybersecurity awareness session",
        details: "Delivered a session at L&T Training Center, Madh Island, With a focus on fostering awareness about cybersecurity. The session, marked by its interactive nature, received exceptional acclaim from the participants. A testament to our commitment to advancing knowledge in the ever-evolving realm of cybersecurity.",
       link: "https://example.com/cybersecurity-awareness",
       banner: "/img/achievements/mp.jpg",
    },
     {
         id: 17,
      name:"Dr. Asha Durafe",
      date: "7th Feb 2024",
      achievement: "Deepfake Session at AI Conclave",
        details: "Delivered a session on Deepfake and Misinformation in AI Conclave, an AI conference sponsored by CyberPeaceat VIT, Bhopal! It was an enlightening experience for her to dive into the complexities and implications of this rapidly evolving field. From understanding the technical intricacies to discussing its impact on society, it’s crucial to stay informed and vigilant in this digital age.",
       link: "https://example.com/deepfake-session",
     banner: "/img/achievements/aiconclave.jpg",
     },
   {
      id: 18,
    name: "CYSE Department",
      date:"8th Jan to 12 Jan 2024",
      achievement:"Completed STTP Successfully",
       details: "This industry academia venture opens a platform for students, faculty and industry professionals to learn from experts and earn international certifications in Cyber Security & Digital Forensics.",
       link: "https://example.com/sttp-training",
      banner: "/img/achievements/sttp.jpg",
  },
  
  {
       id: 20,
    name: "Dr. Nilakshi Jain",
     date: "19th December 2023",
      achievement:"Panellist at Deepfake Consultation",
        details:"Dr. Nilakshi Jain, was invited as a distinguished panellist at the Round Table Consultation on Deepfake Technology. This pivotal event, organized by the National Commission for Women – India (NCW) in collaboration with CyberPeace Foundation Collaborative, unfolded on December 19th, 2023, at the iconic Indian International Center in New Delhi.",
       link: "https://example.com/panellist-round-table",
       banner: "/img/achievements/ncw.jpg",
  },
  {
       id: 21,
     name:"Dr. Nilakshi Jain",
     date: "October 2023",
    achievement:"Research grant of 15 lacs",
    details:"Project “Investigating AI-Driven Misconduct: Deepfake Technology, Fake WhatsApp Calls, and Beyond” has secured a substantial research grant of 15 lacs.",
      link: "https://example.com/research-grant",
      banner: "/img/achievements/driven.jpg",
  },
    {
        id: 22,
      name: "Dr. Nilakshi Jain",
      date: "Jan 2024",
       achievement: "Deepfake Workshop session",
       details: "Dr. Nilakshi Jain, a distinguished expert in the field of cybersecurity, was recently honored with an invitation to deliver a groundbreaking session on “Deepfake” at a prestigious workshop organized by UNSW, United Service Institution of India and CyberPeace Foundation. The workshop emphasized the potential role of Artificial Intelligence (AI) in addressing these challenges. Dr. Jain provided hands-on mitigatory techniques, equipping attendees with practical tools to navigate the complex terrain of misinformation and Deepfakes effectively.",
       link: "https://example.com/deepfake-workshop",
        banner: "/img/achievements/unsw.jpg",
   },
   {
       id: 23,
      name:"SAKEC TE Students",
     date: "9th Dec 2023",
      achievement:"1st Runner-Up at hackathon",
       details: "Congratulations to our Cybersecurity department’s students for securing 1st runner-up at India’s renowned ‘Cffeine Trip’ hackathon! Their innovative solutions and unwavering dedication underscore their prowess in defending digital frontiers. Congratulating students of Shah & anchor department’s pride: 1. Tanvi Humane (TE CYSE) 2. Akshat Adavadkar (TE CYSE)",
       link: "https://example.com/hackathon-runnerup",
        banner: "/img/achievements/ceffeine.jpg",
   },
  {
       id: 24,
      name:"SAKEC TE Students",
    date: "9th Dec 2023",
    achievement:"Winners at hackathon",
     details: "Exceptional achievement alert! Our Cybersecurity students emerge as champions at India’s longest hackathon, ‘Cffeine Trip’! Their ground-breaking solutions and unparalleled expertise set a new standard in cybersecurity. A proud moment for innovation and excellence! Congratulating students of Shah & anchor department’s pride: 1. Krishna Kounder (TE CYSE) 2. Sahil Zunjarrao (TE CYSE) 3. PAXAL DILIP TALAWAT (TE CYSE)",
       link: "https://example.com/hackathon-winners",
       banner: "/img/achievements/trip.jpg",
   },
   {
        id: 25,
     name:"CYSE Student",
      date:"9th Dec 2023",
     achievement: "Best Individual at Hackathon",
     details:"Individual:”Thrilled to congratulate Deepranjan Bhosale Bhosle from our Cybersecurity department for clinching the title of ‘Best Individual’ at ‘Cffeine Trip,’ India’s premier hackathon! His exceptional talent, innovation, and unwavering dedication to cybersecurity have set an inspiring benchmark. Kudos to their outstanding achievement!",
     link: "https://example.com/hackathon-individual",
      banner: "/img/achievements/deept.jpg",
  },
  {
       id: 26,
    name:"SAKEC BE Students",
     date:"9th Dec 2023",
    achievement:"2nd runner-up at hackathon",
     details: "2nd Runner-Up: “Kudos to our Cybersecurity students for achieving 2nd runner-up at India’s prestigious ‘Cffeine Trip’ hackathon! Their dedication and skill in safeguarding digital realms shine bright, showcasing their commitment to excellence in cybersecurity. hashtag#CyberExcellence hashtag#Hackathon Achievement” Congratulating students of Shah & anchor department’s pride: 1. Shreyansh Dave (BE CYSE) 2. Aishwarya Kadam (BE CYSE)",
    link: "https://example.com/hackathon-second-runnerup",
       banner: "/img/achievements/2runnerup.jpg",
   },
    {
         id: 27,
      name:"SAKEC Students",
     date:"1st September, 2023",
      achievement:"Project Launched at CyberPeace Summit",
      details:"SAKEC CyberPeace Centre of Excellence proud to announce that our Research based project got launched in Global CyberPeace Summit and Dialogues a pivotal event supporting G20 India on 1st September, 2023 in United Service Institution, Rao Tula Ram Marg, New Delhi Project Name:  Linux Admin",
      link: "https://example.com/global-cyberpeace-summit",
       banner:"/img/achievements/Linuxa.jpg"
      },
  {
       id: 28,
      name:"SAKEC Students",
      date:"1st September, 2023",
      achievement:"Project Launched at CyberPeace Summit",
      details:"SAKEC CyberPeace Centre of Excellence proud to announce that our Research based project got launched in Global CyberPeace Summit and Dialogues a pivotal event supporting G20 India on 1st September, 2023 in United Service Institution, Rao Tula Ram Marg, New Delhi. Project Name: HoneyTrack",
      link: "https://example.com/global-cyberpeace-summit",
       banner:"/img/achievements/Honeytrack.jpg"
  },
  {
      id: 29,
      name:"SAKEC Students",
        date:"1st September, 2023",
      achievement:"Project Launched at CyberPeace Summit",
       details:"SAKEC CyberPeace Centre of Excellence proud to announce that our Research based project got launched in Global CyberPeace Summit and Dialogues a pivotal event supporting G20 India on 1st September, 2023 in United Service Institution, Rao Tula Ram Marg, New Delhi Project Name:Cygiene",
     link: "https://example.com/global-cyberpeace-summit",
     banner:"/img/achievements/cygiene.jpg"
  },
      {
         id: 30,
       name:"SAKEC Students",
        date:"1st September, 2023",
        achievement:"Project Launched at CyberPeace Summit",
       details: "SAKEC CyberPeace Centre of Excellence proud to announce that our Research based project got launched in Global CyberPeace Summit and Dialogues a pivotal event supporting G20 India on 1st September, 2023 in United Service Institution, Rao Tula Ram Marg, New Delhi Project Name: courage2correct",
        link: "https://example.com/global-cyberpeace-summit",
       banner:"/img/achievements/courage2.jpg"
    },
  {
      id: 31,
    name:"SAKEC Students",
       date: "1st September, 2023",
      achievement:"Project Launched at CyberPeace Summit",
       details:"SAKEC CyberPeace Centre of Excellence proud to announce that our Research based project got launched in Global CyberPeace Summit and Dialogues a pivotal event supporting G20 India on 1st September, 2023 in United Service Institution, Rao Tula Ram Marg, New Delhi Project Name: Capture The Flag",
        link: "https://example.com/global-cyberpeace-summit",
       banner:"/img/achievements/capture.jpg"
  },
  {
       id: 32,
    name:"SAKEC Students",
      date:"1st September, 2023",
      achievement: "Project Launched at CyberPeace Summit",
       details: "SAKEC CyberPeace Centre of Excellence proud to announce that our Research based project got launched in Global CyberPeace Summit and Dialogues a pivotal event supporting G20 India on 1st September, 2023 in United Service Institution, Rao Tula Ram Marg, New Delhi. Project Name : Dark Web",
       link: "https://example.com/global-cyberpeace-summit",
     banner:"/img/achievements/darkweb.jpg"
   },
   {
       id: 33,
     name:"CYSE Students",
     date: "Sept 2023",
      achievement:"Won Intel AI Festival",
       details:"Cyber Security Department Students achieved remarkable success as a Country/Region Winner in the prestigious Intel® AI Global Impact Festival 2023! Winners received prizes worth $1,000 and an Intel certificate. their outstanding AI project has not only showcased their immense talent but has also made a significant contribution to the world of artificial intelligence & cyber security.",
     link: "https://example.com/intel-ai-festival",
     banner:"/img/achievements/intel.jpg"
    },
    {
        id: 34,
      name:"CYSE Department",
      date:"26th July 2023",
       achievement:"Industrial Visit at AIIPLTECH",
       details:"Highlights of the Visit: Engaging presentations on Cyber Security trends and challenges Live demonstrations of state-of-the-art security solutions Networking opportunities with industry professionals Interactive Q&A sessions with Cyber Security specialists",
        link: "https://example.com/industrial-visit",
     banner: "/img/achievements/AIIPL.jpg",
  },
   {
       id: 35,
     name: "CYSE Student",
      date:"24th August 2023",
     achievement: "Trained Indian Airforce",
      details: "On behalf of V4WEB CYBERSECURITY, Shrawani recently conducted an enlightening and impactful training session for none other than the esteemed Indian Airforce, focusing on “Cybersecurity Awareness.” Shrawani’s training session was a resounding success, receiving accolades from the Indian Air Force for her expertise and dedication to the field of cybersecurity.",
     link: "https://example.com/indian-airforce-training",
    banner: "/img/achievements/shravani.jpg",
  },
  {
       id: 36,
       name:"CYSE Department",
      date:"10th to 13th June 2023",
     achievement: "Technical Team Member at CCTNS",
      details:"Mr. Mustaansir Godhrawala contributed his expertise as a member of the technical team, engaging with brilliant minds in cybersecurity and witnessing cutting-edge solutions.",
     link: "https://example.com/cctns-hackathon",
    banner: "/img/achievements/mustansir.jpg",
  },
     {
        id: 37,
      name:"Cybersecurity Department",
         date:"16th March 2023",
      achievement:"Launched Startup: CyHEX Infotech",
       details: "Startup is all about providing development, products, and services that make a difference.  Every project is unique, and they work closely with their clients to understand their needs and deliver customized solutions. Thier goal is to make technology accessible and easy for everyone.",
      link: "https://example.com/cyhex-infotech",
     banner: "/img/achievements/cyhax.jpg",
    },
  {
       id: 38,
    name:"Dr. Nilakshi Jain",
      date:"July 2023",
    achievement: "Shortlisted Cybersecurity Woman of Year",
    details: "Her exceptional talent, dedication, and significant contributions to the field of cybersecurity have earned her a place among an exceptional group of women. This year's awards have surpassed all expectations, attracting an unprecedented number of outstanding nominees from around the world. From New Zealand to Moldova, Macedonia to Ukraine, Philippines to Egypt, Kuwait to Australia, Italy to the Netherlands, Zimbabwe to Peru, and over 60 other remarkable countries, the diversity and global impact of women in cybersecurity shine brightly.",
    link: "https://example.com/cybersecurity-woman",
   banner: "/img/achievements/NJ-award.jpg",
  },
   {
      id:39,
      name:"CYSE Department",
    date:"25th April 2023",
     achievement: "Magazine Abhayam Launch",
      details:"Event was held on 25th April 2023 in the presence of respected Trustees, Principal Dr Bhavesh Patel ,HoDs , faculties, and Cyber Security Council members.",
     link: "https://example.com/magazine-abhayam",
     banner:"/img/achievements/magazine.jpg",
   },
  {
       id: 40,
      name:"CYSE Department",
     date:"Jan 2023",
       achievement: "CEH Course Performance",
      details:"Total of 27 candidates registered and 25 candidates successfully completed the certification.",
      link: "https://example.com/ceh-participants",
      banner: "/img/achievements/CEH-2023.jpg",
  },

 {
        id: 42,
      name: "Dr. Nilakshi Jain",
      date: "19 May 2022",
      achievement: "Scored 91% at CHFI certification",
        details: "EC-Council",
        link: "https://example.com/chfi-certification",
    banner: "/img/achievements/nj-forensic.jpg",
    },
];

export default achievementsData;