// src/data/CopyrightsData.js
export const copyrightsData = [
    {
      diaryNo: "27971/2021-CO/L",
      applicantName: [
        "Shruti Dantala",
        "Shivam Pandit",
        "Rutuja Umap",
        "Shwetambari Borade",
      ],
      titleOfWork: "Ace Guard",
      departmentName: "Cyber Security",
      status: "Registered",
      copyrightCertificateReceivedDate: "Friday,February 11,2022",
      rocNumber: "L-111821/2022",
      dateAppliedForCopyright: "11/19/2021",
      ay: "2021-22",
    },
    {
      diaryNo: "27949/2021-CO/L",
      applicantName: [
        "Aishwarya Kadam",
        "Muskan Rathod",
        "Harsh Raul",
        "Shwetambari Borade",
      ],
      titleOfWork: "AES ENCRYPTION WITH CUSTOM CYPHER",
      departmentName: "Cyber Security",
      status: "Registered",
      copyrightCertificateReceivedDate: "Friday,February 11,2022",
      rocNumber: "L-111822/2022",
      dateAppliedForCopyright: "11/19/2021",
      ay: "2021-22",
    },
    {
      diaryNo: "28018/2021-CO/L",
      applicantName: [
        "Atharva Kothawade",
        "Sakshi Dhanawade",
        "Rammya Sakpal",
        "Ojas Patil",
        "Dr. Nilakshi Jain",
      ],
      titleOfWork: "Secure Book Explorer",
      departmentName: "Cyber Security",
      status: "Registered",
      copyrightCertificateReceivedDate: "25/01/2022",
      rocNumber: "L-111099/2022",
      dateAppliedForCopyright: "11/20/2021",
      ay: "2021-22",
    },
    {
      diaryNo: "28022/2021-CO/L",
      applicantName: [
        "Shaik Mohammed Izaan",
        "Drashti Nagda",
        "Prerana Patil",
        "Ms. Nawal Dandekar",
      ],
      titleOfWork: "Data Concealing using Cryptography and Steganography",
      departmentName: "Cyber Security",
      status: "Registered",
      copyrightCertificateReceivedDate: "31/01/2022",
      rocNumber: "L-111404/2022",
      dateAppliedForCopyright: "11/20/2021",
      ay: "2021-22",
    },
    {
      diaryNo: "28029/2021-CO/L",
      applicantName: [
        "Atharva Sachin Auti",
        "Vivek Kaliprasad Mishra",
        "Jay Ashwinkumar Makwana",
        "Shrawani JS Pagar",
        "Shwetambari Borade",
      ],
      titleOfWork: "HoneyTrack",
      departmentName: "Cyber Security",
      status: "Registered",
      copyrightCertificateReceivedDate: "Friday,February 11,2022",
      rocNumber: "L-111817/2022",
      dateAppliedForCopyright: "11/20/2021",
      ay: "2021-22",
    },
    {
      diaryNo: "28044/2021-CO/L",
      applicantName: [
        "Ritvik Rajesh Karbhari",
        "Sudip Dilip Khotkar",
        "Aditya Durgachand Panda",
        "Sahil Rajnikanth Raulo",
        "Shwetambari Borade",
      ],
      titleOfWork: "Ransomware attack and its prevention",
      departmentName: "Cyber Security",
      status: "Registered",
      copyrightCertificateReceivedDate: "25/01/2022",
      rocNumber: "L-111190/2022",
      dateAppliedForCopyright: "11/20/2021",
      ay: "2021-22",
    },
    {
      diaryNo: "28062/2021-CO/L",
      applicantName: [
        "Prasad Pralhad Madye",
        "Khan Umar Mohommedayub",
        "Mohammad Saqib Ashfaque Ahmad",
        "Dr. Nilakshi Jain",
        "Vishakha Shinde",
      ],
      titleOfWork: "Image Encryption and Decryption using AES Algorithm",
      departmentName: "Cyber Security",
      status: "Registered",
      copyrightCertificateReceivedDate: "31/01/2022",
      rocNumber: "L-111406/2022",
      dateAppliedForCopyright: "11/21/2021",
      ay: "2021-22",
    },
    {
      diaryNo: "28064/2021-CO/L",
      applicantName: [
        "Jash Yogesh Bhanushali",
        "Kaiwalya Raju Mungase",
        "Vishal Parag Padia",
        "Sahil Ramchandra Sakapal",
        "Dr. Nilakshi Jain",
      ],
      titleOfWork: "HONEYPOT-THE TOOL OF DECEPTION",
      departmentName: "Cyber Security",
      status: "Registered",
      copyrightCertificateReceivedDate: "31/01/2022",
      rocNumber: "L-111407/2022",
      dateAppliedForCopyright: "11/21/2021",
      ay: "2021-22",
    },
    {
      diaryNo: "28066/2021-CO/L",
      applicantName: [
        "Kshitij Siddharth Sonawane",
        "Shubham Rajaram More",
        "Sanket Anil Singh",
        "Nawal Dandekar",
      ],
      titleOfWork: "Three Level Password Authentication System",
      departmentName: "Cyber Security",
      status: "Registered",
      copyrightCertificateReceivedDate: "25/01/2022",
      rocNumber: "L-111100/2022",
      dateAppliedForCopyright: "11/21/2021",
      ay: "2021-22",
    },
    {
      diaryNo: "28067/2021-CO/L",
      applicantName: [
        "Sahil Girish Bhanushali",
        "Het Viren Chheda",
        "Aditya Ajit Kamble",
        "Shwetambari Borade",
        "Vishakha Shinde",
      ],
      titleOfWork: "Image Watermarking Using Dct",
      departmentName: "Cyber Security",
      status: "Registered",
      copyrightCertificateReceivedDate: "31/01/2022",
      rocNumber: "L-111408/2022",
      dateAppliedForCopyright: "11/21/2021",
      ay: "2021-22",
    },
    {
      diaryNo: "28069/2021-CO/L",
      applicantName: [
        "Aditya Ramesh Patel",
        "Vedant Shridhar Parte",
        "Aryan Jugal Doshi",
        "Nawal Dandekar",
      ],
      titleOfWork: "Cross-Site Scripting(xss)",
      departmentName: "Cyber Security",
      status: "Registered",
      copyrightCertificateReceivedDate: "25/01/2022",
      rocNumber: "L-111409/2022",
      dateAppliedForCopyright: "11/21/2021",
      ay: "2021-22",
    },
    {
      diaryNo: "28070/2021-CO/L",
      applicantName: [
        "Preet Hiren Kansara",
        "Pritam Dilip Jain",
        "Vaidehi Mangesh Salvi",
        "Shwetambari Borade",
      ],
      titleOfWork: "Encryption and Decryption with Caesar Cipher",
      departmentName: "Cyber Security",
      status: "Registered",
      copyrightCertificateReceivedDate: "25/01/2022",
      rocNumber: "L-111102/2022",
      dateAppliedForCopyright: "11/21/2021",
      ay: "2021-22",
    },
    {
      diaryNo: "28072/2021-CO/L",
      applicantName: [
        "Aabha Arvind Wagh",
        "Milind Narsingrao Sunkari",
        "Pramod Balu virkar",
        "Nawal Dandekar",
      ],
      titleOfWork: "Android Text Encryption Application",
      departmentName: "Cyber Security",
      status: "Registered",
      copyrightCertificateReceivedDate: "31/01/2022",
      rocNumber: "L-111410/2022",
      dateAppliedForCopyright: "11/21/2021",
      ay: "2021-22",
    },
    {
      diaryNo: "28074/2021-CO/L",
      applicantName: [
        "Umang Sharad Bhanushali",
        "Mustansir Sazid Godhrawala",
        "Chetan Prakash Gajbe",
        "Dr. Nilakshi Jain",
      ],
      titleOfWork: "Cybersecurity and Data Privacy Legislature Review Article",
      departmentName: "Cyber Security",
      status: "Registered",
      copyrightCertificateReceivedDate: "31/01/2022",
      rocNumber: "L-111411/2022",
      dateAppliedForCopyright: "21/11/2021",
      ay: "2021-22",
    },
    {
      diaryNo: "7767/2022-CO/L",
      applicantName: [
        "Rakesh Patel",
        "Yatin Rathod",
        "Mirthunjai Yadav",
        "Ms. Meghali Kalyankar",
      ],
      titleOfWork: "BROWSER PASSWORD DECODER",
      departmentName: "Cyber Security",
      status: "Registered",
      copyrightCertificateReceivedDate: "22/11/2022",
      rocNumber: "L-118973/2022",
      dateAppliedForCopyright: "12/4/2022",
      ay: "2022-23",
    },
    {
      diaryNo: "7773/2022-CO/L",
      applicantName: [
        "Mr. Tushar Patil",
        "Mr. Pranay Patil",
        "Mr. Atharva Dhuri",
        "Mr. Shailendra Kumane",
      ],
      titleOfWork: "Triple DES",
      departmentName: "Cyber Security",
      status: "Registered",
      copyrightCertificateReceivedDate: "22/11/2022",
      rocNumber: "L-118972/2022",
      dateAppliedForCopyright: "12/4/2022",
      ay: "2022-23",
    },
    {
      diaryNo: "12340/2022-CO/L",
      applicantName: [
        "Patel Darsh Bharat",
        "Rathore Dimple Magaram",
        "Avhad Niyati Anil",
        "Ms. Meghali Kalyankar",
        "Shah and Anchor Kuttchi Engineering College",
      ],
      titleOfWork: "ANDROID TEXT ENCRYPTION AND DECRYPTION",
      departmentName: "Cyber Security",
      status: "Registered",
      copyrightCertificateReceivedDate: "10/10/2022",
      rocNumber: "L-118086/2022",
      dateAppliedForCopyright: "10/6/2022",
      ay: "2022-23",
    },
    {
      diaryNo: "27781/2022-CO/L",
      applicantName: [
        "VISHAKHA RAMCHANDRA SHINDE",
        "TANVI HUMANE",
        "KRISHNA KOUNDER",
        "SHUBHAM SHARMA",
        "ANUBHAV VERMA",
        "SHAH & ANCHOR KUTCHHI ENGINEERING COLLEGE",
      ],
      titleOfWork: "Cam phishing and its prevention",
      departmentName: "Cyber Security",
      status: "Registered",
      copyrightCertificateReceivedDate: "3/11/2023",
      rocNumber: "L-135320/2023",
      dateAppliedForCopyright: "31/12/2022",
      ay: "2023-24",
    },
    {
      diaryNo: "26526/2022-CO/L",
      applicantName: ["DR ASHA DURAFE,"],
      titleOfWork: "Host based intrusion detection system",
      departmentName: "Cyber Security",
      status: "Registered",
      copyrightCertificateReceivedDate: "12/6/2023",
      rocNumber: "L-124741/2023",
      dateAppliedForCopyright: "20/12/2022",
      ay: "2022-23",
    },
    {
      diaryNo: "26343/2022-CO/L",
      applicantName: ["DR ASHA DURAFE,"],
      titleOfWork: "MiTM using custom packet sniffer",
      departmentName: "Cyber Security",
      status: "Registered",
      copyrightCertificateReceivedDate: "9/6/2023",
      rocNumber: "L-124636/2023",
      dateAppliedForCopyright: "17/12/2022",
      ay: "2022-23",
    },
    {
      diaryNo: "26373/2022-CO/L",
      applicantName: [
        "MEGHALI AJAY KALYANKAR",
        "DEEP ARVIND PARASIYA,",
        "SAHIL RAJU PIMPLE",
        "JIGAR BHARAT OJHA",
        "RAHUL SANTANU JANA",
      ],
      titleOfWork: "Recon Tool Vulnerability Assessment",
      departmentName: "Cyber Security",
      status: "Registered",
      copyrightCertificateReceivedDate: "12/10/2023",
      rocNumber: "L-134657/2023",
      dateAppliedForCopyright: "17/12/2022",
      ay: "2023-24",
    },
    {
      diaryNo: "26318/2022-CO/L",
      applicantName: ["DR ASHA DURAFE"],
      titleOfWork: "Survey paper based critical reviews for image tampering detection",
      departmentName: "Cyber Security",
      status: "Registered",
      copyrightCertificateReceivedDate: "9/6/2023",
      rocNumber: "L-124632/2023",
      dateAppliedForCopyright: "17/12/2022",
      ay: "2022-23",
    },
    {
      diaryNo: "27136/2022-CO/L",
      applicantName: ["RASHMI PIYUSH PATEL"],
      titleOfWork: "VULNERABILITY SCANNER AND REPORT GENERATION",
      departmentName: "Cyber Security",
      status: "Registered",
      copyrightCertificateReceivedDate: "8/11/2023",
      rocNumber: "L-135707/2023",
      dateAppliedForCopyright: "26/12/2022",
      ay: "2023-24",
    },
    {
      diaryNo: "27119/2022-CO/L",
      applicantName: ["RASHMI PIYUSH PATEL"],
      titleOfWork: "Comparative Analysis Between Types of Viruses and Antivirus",
      departmentName: "Cyber Security",
      status: "Registered",
      copyrightCertificateReceivedDate: "8/11/2023",
      rocNumber: "L-135705/2023",
      dateAppliedForCopyright: "26/12/2022",
      ay: "2023-24",
    },
    {
      diaryNo: "26701/2022-CO/L",
      applicantName: [
        "VISHAKHA SHINDE",
        "MEHUL SHARMA",
        "PIYUSH SINGH",
        "PRASAD SALVE",
        "PRATHAMESH SAGVEKAR",
      ],
      titleOfWork: "Packet Sniffing",
      departmentName: "Cyber Security",
      status: "Registered",
      copyrightCertificateReceivedDate: "30/08/2023",
      rocNumber: "L-132664/2023",
      dateAppliedForCopyright: "21/12/2022",
      ay: "2023-24",
    },
    {
      diaryNo: "27531/2022-CO/L",
      applicantName: [
        "RASHMI P PATEL",
        "AISHWARYA VILAS KADAM",
        "RATHOD MUSKAN RANCHHOD",
        "HARSH RAJESH RAUL",
      ],
      titleOfWork: "NEMISIS",
      departmentName: "Cyber Security",
      status: "Registered",
      copyrightCertificateReceivedDate: "20/10/2023",
      rocNumber: "L-134912/2023",
      dateAppliedForCopyright: "26/12/2022",
      ay: "2023-24",
    },
    {
      diaryNo: "27611/2022-CO/L",
      applicantName: [
        "VISHAKHA RAMCHANDRA SHINDE",
        "NIYATI ANIL AVHAD",
        "DIMPLE MAGARAM RATHORE",
        "DARSH BHARAT PATEL",
        "YATIN MAHESH RATHOD",
        "SHAH & ANCHOR KUTCHHI ENGINEERING COLLEGE",
      ],
      titleOfWork: "WEB RECON",
      departmentName: "Cyber Security",
      status: "Registered",
      copyrightCertificateReceivedDate: "26/06/2023",
      rocNumber: "L-127247/2023",
      dateAppliedForCopyright: "30/12/2022",
      ay: "2022-23",
    },
    {
      diaryNo: "26974/2022-CO/L",
      applicantName: [
        "DEEPIKA BURTE",
        "YASH NAGARE",
        "DEEPRANJAN BHOSALE",
        "DEVENDRA MISHRA",
        "NILAKSHI JAIN",
        "Shah & Anchor Kutchhi Engineering College",
      ],
      titleOfWork: "Authentication and Detection of Morph Photograph and Tampering",
      departmentName: "Cyber Security",
      status: "Registered",
      copyrightCertificateReceivedDate: "09/06/2023",
      rocNumber: "L-124632/2023",
      dateAppliedForCopyright: "23/12/2022",
      ay: "2022-23",
    },
    {
      diaryNo: "27660/2022-CO/SW",
      applicantName: [
        "MEGHALI AJAY KALYANKAR",
        "DARSH PATEL",
        "PARSHVA DOSHI",
        "RAMMYA SAKPAL",
      ],
      titleOfWork: "THREAT VENATIO",
      departmentName: "Cyber Security",
      status: "Registered",
      copyrightCertificateReceivedDate: "27/06/2023",
      rocNumber: "SW-16678/2023",
      dateAppliedForCopyright: "30/12/2022",
      ay: "2022-23",
    },
    {
      diaryNo: "4523/2024-CO/SW",
      applicantName: [
        "KOUNDER KRISHNA RAJENDRA",
        "HUMANE TANVI AJAY",
        "GUPTA PRATIK PRAVEEN",
        "ISMULWAR HARSHAL RAJU",
        "DR. ASHA VIJAY DURAFE",
      ],
      titleOfWork: "Detecting real IP address behind VPN and proxy servers",
      departmentName: "Cyber Security",
      status: "Registered",
      copyrightCertificateReceivedDate: "14/01/2025",
      rocNumber: "SW-20081/2025",
      dateAppliedForCopyright: "9/2/2024",
      ay: "2024-25",
    },
    {
      diaryNo: "6417/2024-CO/SW",
      applicantName: [
        "VEDANT SHRIDHAR PARTE",
        "ARYAN DOSHI",
        "MUNGASE KAIWALYA RAJU",
        "HET VIREN CHHEDA",
        "DR. ASHA DURAFE",
      ],
      titleOfWork: "Malware probe",
      departmentName: "Cyber Security",
      status: "Registered",
      copyrightCertificateReceivedDate: "9/5/2024",
      rocNumber: "SW-18763/2024",
      dateAppliedForCopyright: "28/2/2024",
      ay: "2023-24",
    },
    {
      diaryNo: "2711/2024-CO/SW",
      applicantName: [
        "SHWETAMBARI BORADE",
        "DARSH BHAVESH PATEL",
        "PARSHVA DOSHI",
        "DARSH BHARAT PATEL",
        "OMAKR PRAVIN SOLANKI",
        "Shah & Anchor Kutchhi Engineering College",
      ],
      titleOfWork: "MaliceSpotter",
      departmentName: "Cyber Security",
      status: "Registered",
      copyrightCertificateReceivedDate: "22/10/2024",
      rocNumber: "SW-19581/2024",
      dateAppliedForCopyright: "24/1/24",
      ay: "2024-25",
    },
    {
      diaryNo: "9434/2024-CO/SW",
      applicantName: [
        "Sanket Singh",
        "Shubham More",
        "Kshitj Sonawane",
        "Milind Sunkari",
        "Ms.Meghali Kalyankar",
        "Shah & Anchor Kutchhi Engineering College",
      ],
      titleOfWork: "Evidence Vault",
      departmentName: "Cyber Security",
      status: "Registered",
      copyrightCertificateReceivedDate: "20-06-2024",
      rocNumber: "SW-19048/2024",
      dateAppliedForCopyright: "28/03/2024",
      ay: "2023-24",
    },
  ];