//src/app/projects/ProjectsData.js
export const projectsData = [
    {
      sNo: 1,
      productName: "HackTheWay: Challenge, Learn, Secure",
      faculty: "Dr. Nilakshi Jain, Dr. Shwetambari Borade",
      students: "Nagare Yash Anant, Mishra Devendra Pravinkumar, Saini Jasjyot Singh, Tawade Gayatri Prabhakar",
      academicYear: "2024-25",
      shortIntro: "HackTheWay: Challenge, Learn, Secure",
    },
    {
      sNo: 2,
      productName: "CAPS(Centralised Administrative Portal For SNMP)",
      faculty: "Dr. Bhavesh Patel, Dr. Nilakshi Jain",
      students: "Bhosale Deepranjan Prashant, Parasiya Deep Arvind, Pimple Sahil Raju",
      academicYear: "2024-25",
      shortIntro: "CAPS(Centralised Administrative Portal For SNMP)",
    },
    {
      sNo: 3,
      productName: "HealthChain Vault: Secure Digital Health Locker",
      faculty: "Dr. Bhavesh Patel, Dr. Rupali Vairagade",
      students: "Shah Sameer Anilkumar, Shah Krish Parag, Salve Prasad Sopan, Ojha Jigar Bharat",
      academicYear: "2024-25",
      shortIntro: "HealthChain Vault: Secure Digital Health Locker",
    },
    {
      sNo: 4,
      productName: "File storage using hybrid cryptography",
      faculty: "Dr. Rupali Vairagade",
      students: "Ismulwar Harshal Raju, Gupta Manoj Ramashish, Yadav Shailesh Hiralal",
      academicYear: "2024-25",
      shortIntro: "File storage using hybrid cryptography",
    },
    {
      sNo: 5,
      productName: "ABP (Auto Burn PDF Dynamic PDF Retention Policy",
      faculty: "Dr. Shwetambari Borade",
      students: "Mavani Siddhant Mayank, Verma Anubhav Ravindra, Kounder Krishna Rajendra",
      academicYear: "2024-25",
      shortIntro: "ABP (Auto Burn PDF Dynamic PDF Retention Policy",
    },
    {
      sNo: 6,
      productName: "Crime Reporting Dashboard",
      faculty: "Dr. Shwetambari Borade",
      students: "Adavadkar Akshat Dinesh, Doshi Drashti Jitendra, Gaikwad Arya Gulab, Prajapati Chirag Mohan",
      academicYear: "2024-25",
      shortIntro: "Crime Reporting Dashboard",
    },
    {
      sNo: 7,
      productName: "SecuCode: Secure Coding Program for Practical Exams",
      faculty: "Ms Vishakha Shinde",
      students: "Mewada Pratham Sanjeev, Kotadia Jainish Ritesh, Manani Sharad Hemraj",
      academicYear: "2024-25",
      shortIntro: "SecuCode: Secure Coding Program for Practical Exams",
    },
    {
      sNo: 8,
      productName: "Ransomware Analysis Using Machine Learning",
      faculty: "Ms Vishakha Shinde",
      students: "Dedhia Devang Ashwin, Gupta Pratik Pravin, Narvekar Amey Pravin, Shaikh Needa Kaiser",
      academicYear: "2024-25",
      shortIntro: "Ransomware Analysis Using Machine Learning",
    },
    {
      sNo: 9,
      productName: "Unmasking Digital Impersonation: Financial Fraud via Deepfakes",
      faculty: "Dr. Nilakshi Jain, Ms. Vishakha Shinde",
      students: "Koli Yash Pratap, Talawat Paxal Dilip, Wagh Kedar Prashant, Zunjarrao Sahil Shailesh",
      academicYear: "2024-25",
      shortIntro: "Unmasking Digital Impersonation: Financial Fraud via Deepfakes",
    },
    {
      sNo: 10,
      productName: "Secure Sphere : Learn Protect Secure",
      faculty: "Ms. Meghali Kalyankar",
      students: "Jogi Raj Kamlesh, Narkar Viraj Anant, Menor Brijraj Singh Avinash Singh, Dighe Sujal Dinkar",
      academicYear: "2024-25",
      shortIntro: "Secure Sphere : Learn Protect Secure",
    },
    {
      sNo: 11,
      productName: "Fraudlens: Unmasking Digital Deceit",
      faculty: "Ms. Meghali Kalyankar",
      students: "Shaikh Zoheir Shahid, Gajra Om Pratap, Sharma Mehul Lalit, Sagvekar Prathamesh Vilas",
      academicYear: "2024-25",
      shortIntro: "Fraudlens: Unmasking Digital Deceit",
    },
    {
      sNo: 12,
      productName: "Cyber Suraksha: Empowering Digital Safety for a Secure Future",
      faculty: "Dr. Bhavesh Patel, Ms. Meghali Kalyankar",
      students: "Bhelkar Sahil Abhijay, Jana Rahul Santanu, Kathepuri Vaibhavi Sanjay, Tupat Yash Kishor",
      academicYear: "2024-25",
      shortIntro: "Cyber Suraksha: Empowering Digital Safety for a Secure Future",
    },
    {
      sNo: 13,
      productName: "TAML - Trap Analysis Monitor Logs",
      faculty: "Dr. Bhavesh Patel, Ms Priyanka Singh",
      students: "Sharma Shubham Rajesh, Singh Piyush Chandrashekhar, Shanbhag Sanjana Ashok",
      academicYear: "2024-25",
      shortIntro: "TAML - Trap Analysis Monitor Logs",
    },
    {
      sNo: 14,
      productName: "PT-SecPro: Advanced Penetration Testing Suite",
      faculty: "Dr. Rupali Vairagade",
      students: "Tandekar Kartik Krishna, Rane Mrunal Aashish, Babar Sanket Santosh, Avhad Niyati Anil",
      academicYear: "2024-25",
      shortIntro: "PT-SecPro: Advanced Penetration Testing Suite",
    },
    {
      sNo: 15,
      productName: "Critical Security Alert: Suspicious Message Detected",
      faculty: "Dr. Rupali Vairagade",
      students: "Kotkar Kaushal Kailas, Deore Samiran Satish, Deshmukh Tejal Shailesh, Tak Riddhi Suresh",
      academicYear: "2024-25",
      shortIntro: "Critical Security Alert: Suspicious Message Detected",
    },
    {
      sNo: 16,
      productName: "VulnVigil:Application Dangerous Permissions Analyzer",
      faculty: "Ms Vishakha Shinde",
      students: "Tripathi Dhruvesh Mukesh, Thakur Samannyu Pramod, Tikone Kanav Anil, Tripathi Neha Vinay",
      academicYear: "2024-25",
      shortIntro: "VulnVigil:Application Dangerous Permissions Analyzer",
    },
    {
      sNo: 17,
      productName: "File Malware Removal and Ensuring Malware-Free Files",
      faculty: "Dr. Nilakshi Jain, Dr. Shwetambari Borade",
      students: "Patil Varun Arvind, Patiyane Vedant Ashok, Yadav Keshav Kumar Ramdhani, Prajapati Supriya Rambujhavan",
      academicYear: "2024-25",
      shortIntro: "File Malware Removal and Ensuring Malware-Free Files",
    },
    {
      sNo: 18,
      productName: "MaliceSpotter",
      faculty: "Ms. Shwetambari Borade",
      students: "Doshi Parshva Chetan, Patel Darsh Bhavesh, Solanki Omkar Pravin, Patel Darsh Bharat",
      academicYear: "2024-25",
      shortIntro: "MaliceSpotter",
    },
    {
      sNo: 19,
      productName: "Server side IDS",
      faculty: "Ms. Vishakha Shinde",
      students: "Khotkar Sudip Dilip, Bhanushali Umang Sharad, Dantala Shruti Shridhar, Pandit Shivam Devchandra",
      academicYear: "2024-25",
      shortIntro: "Server side IDS",
    },
    {
      sNo: 20,
      productName: "PowerSecOps",
      faculty: "Dr. Asha Durafe",
      students: "Jain Dhruvil Dilip, Patel Avi Sanjay, Shah Smit Bhavesh, Doshi Mihir Deepak",
      academicYear: "2024-25",
      shortIntro: "PowerSecOps",
    },
    {
      sNo: 21,
      productName: "Leveraging Generative AI for Automated Security Testing in DevSecOps",
      faculty: "Dr. Nilakshi Jain",
      students: "Auti Atharva Sachin, Mishra Vivek Kaliprasad, Makwana Jay Ashwinkumar, Pagar Shrawani Jagadish",
      academicYear: "2024-25",
      shortIntro: "Leveraging Generative AI for Automated Security Testing in DevSecOps",
    },
    {
      sNo: 22,
      productName: "DETEK- AI",
      faculty: "Ms. Shwetambari Borade, Ms. Deepika Burte",
      students: "Nagda Drashti Shailesh, Wagh Aabha Arvind, Savla Parth Hitesh, Salvi Vaidehi Mangesh",
      academicYear: "2024-25",
      shortIntro: "DETEK- AI",
    },
    {
      sNo: 23,
      productName: "Contrabot-Dark Web Crawler",
      faculty: "Dr. Asha Durafe",
      students: "Godhrawala Mustansir Sazid, Dhanawade Sakshi Ankush, Padia Vishal Parag, Dave Shreyansh Hitesh",
      academicYear: "2024-25",
      shortIntro: "Contrabot-Dark Web Crawler",
    },
    {
      sNo: 24,
      productName: "Malware Probe",
      faculty: "Dr. Asha Durafe",
      students: "Mungase Kaiwalya Raju, Chheda Het Viren, Doshi Aryan Jugal, Parte Vedant Shridhar",
      academicYear: "2024-25",
      shortIntro: "Malware Probe",
    },
    {
      sNo: 25,
      productName: "NEMESIS",
      faculty: "Ms. Meghali Kalyankar",
      students: "Kadam Aishwarya Vilas, Patil Ojas Milind, Rathod Muskan Ranchhod, Umap Rutuja Mahesh",
      academicYear: "2024-25",
      shortIntro: "NEMESIS",
    },
    {
      sNo: 26,
      productName: "Cygiene",
      faculty: "Ms. Shwetambari Borade", // Changed faculty to Ms. Shwetambari Borade as per new data, removed others to avoid duplication if it was intended to be a different project. If it's the same project with multiple guides, list all guides.
      students: "Karbhari Ritvik Rajesh, Shaik Mohammed Izaan Mohammed Shakeel, Panda Aditya Durgacharan, Raulo Sahil Rajanikant",
      academicYear: "2024-25",
      shortIntro: "Cygiene", // Assuming same short intro, adjust if needed.
    },
    {
      sNo: 27,
      productName: "ThreatScope Analyzer",
      faculty: "Dr. Asha Durafe",
      students: "Bhanushali Sahil Girish, Patil Tushar Santosh, Poojari Pratham Shridhar, Yadav Mirthunjai Ujagir",
      academicYear: "2024-25",
      shortIntro: "ThreatScope Analyzer",
    },
    {
      sNo: 28,
      productName: "Intrusion Detection System(IDS)",
      faculty: "Ms. Meghali Kalyankar",
      students: "Khan Umar Mohommedayub, Sakpal Sahil Ramchandra, Ail Aniketh Indiresh, Solanki Safwaan Abdul Jabbar",
      academicYear: "2024-25",
      shortIntro: "Intrusion Detection System(IDS)",
    },
    {
      sNo: 29,
      productName: "CyberPro Suite",
      faculty: "Ms. Shwetambari Borade",
      students: "Mohammad Saqib, Rathod Yatin Mahesh, Rathore Dimple Magaram",
      academicYear: "2024-25",
      shortIntro: "CyberPro Suite",
    },
    {
      sNo: 30,
      productName: "EvidenceVault",
      faculty: "Ms. Meghali Kalyankar",
      students: "More Shubham Rajaram, Sonawane Kshitij Siddharth, Singh Sanket Anil, Sunkari Milind Narsingrao",
      academicYear: "2024-25",
      shortIntro: "EvidenceVault",
    },
    {
      sNo: 31,
      productName: "Secure Chain",
      faculty: "Ms. Vishakha Shinde",
      students: "Madye Prasad Pralhad, Bhanushali Jash Yogesh, Raul Harsh Rajesh, Patel Aditya Ramesh",
      academicYear: "2024-25",
      shortIntro: "Secure Chain",
    },
    {
      sNo: 32,
      productName: "AuthenCARD",
      faculty: "Ms. Vishakha Shinde",
      students: "Dhuri Atharva Deepak, Kamtekar Pratham Nandkishor, Kamble Aditya Ajit, Patil Pranay Vilas",
      academicYear: "2024-25",
      shortIntro: "AuthenCARD",
    },
    {
      sNo: 33,
      productName: "OpenEye",
      faculty: "Ms. Prajakta Pote",
      students: "Jain Pritam Dilip, Gajbe Chetan Prakash",
      academicYear: "2024-25",
      shortIntro: "OpenEye",
    },
    {
      sNo: 34,
      productName: "Courage2Correct",
      faculty: "Dr. Nilakshi Jain",
      students: "Sakpal Rammya Rohit, Patil Rushikesh Balwant",
      academicYear: "2024-25",
      shortIntro: "Courage2Correct",
    },
    {
      sNo: 35,
      productName: "Tweetcatcher",
      faculty: "Ms. Vishakha Shinde",
      students: "Preet Hiren Kansara, Prerana Ashok Patil, Pramod Balu Virkar, Rakesh Prakash Patel",
      academicYear: "2024-25",
      shortIntro: "Tweetcatcher",
    },
  ];